### ISSUE TITLE
netstandard2.0

### ISSUE THREAD

**Issue by Rerago** [LoL-Fantome/LeagueToolkit#132]
I tried to activate `netstandard2.0` as TargetFramework. But this is not so easy. Apart from a few changes in the project, the following packages unfortunately do not support 2.0

<s>XXHash3.NET => No support for 2.0</s>
<s>ZstdSharp => No support for 2.0</s>

<s>` Crauzer/ZstdSharp` could possibly be replaced by `oleg-st/ZstdSharp` but I didn't look into that. For `Crauzer/XXHash3.NET` I don`t know a replacement right now.</s>

I would not release a version of my tool in `.NET Framework 4.7.2`. Because this is natively installed on almost all Windows versions and therefore the EXE remains extremely small. `netstandard2.0`

**Comment by Rerago** [comment]
I have crossed out the part with `Crauzer/ZstdSharp`. Now it is actually only `Crauzer/XXHash3.NET`.

**Comment by Crauzer** [comment]
Why would you want to target .net standard 2.0?
We should aim to target .NET 6 since that's an LTS release.

**Comment by Rerago** [comment]
The question is rather: Why not?

.NET 6 support is already given by .net standard 2.1. I would make a multi-target and build for 2.0 and 2.1. So far all currently supported frameworks would be covered. 

I think a lib should support all currently supported frameworks as far as possible.

**Comment by Crauzer** [comment]
Why not ? Because these old frameworks such as .NET Standard and .NET Core are now obsolete ever since .NET 5 came out.
.NET 6 is what we want to target for all projects, that way you get the newest language version and features.
I do not wish to support old frameworks just because someone can't upgrade.

**Comment by Rerago** [comment]
Ok your decision. 

However, .net standard 2.0 support doesn't hurt anyone. And the old frameworks are not obsolete as long as they are still supported.

And as said above, normally a library should provide a wide span. Since the application should determine the target framework and not the library. That's the reason why .net standard exists at all.

**Comment by Rerago** [comment]
Since XXHash3.NET now supports netstandard2.0 we could take care of the whole thing again. But since I think we should wait until the refectoring is done.

**Comment by Morilli** [comment]
I would much rather try and use modern features while targeting .net6 / .net7 tbh.

**Comment by Crauzer** [comment]
I have encountered a very strange issue with the `System.Memory` polyfills when working on the new `XXHash3` streaming code and I need to investigate further to see if it was just some random bug.
Either way, if we do want to support `.NET Standard 2.0` we will have to rewrite all a lot of the code afterwards with ugly polyfill hacks which is a big turnoff for no real reward - something to consider.

**Comment by Rerago** [comment]
When I opened the issue, changes were actually quite marginal (that might change with refactoring). Currently I am using `.NET 6` myself for my tool, so it doesn't bother me at the moment.

I always find it a bit of a pity for a library when officially supported frameworks are not supported. And `.NET 4.7` is still supported:

https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

But it's also totally ok if you don't hold this opinion. Then we can close this issue (I have already cleaned up my other issues that were still open).

**Comment by Crauzer** [comment]
I think Microsoft is still supporting the ancient .NET Framework likely because there are still a lot of legacy enterprise systems built on it. I don't think anybody uses these old frameworks anymore unless they have no choice due to some strange reasons.

[Here is a nice guide for how to target correctly](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#net-5-and-net-standard)

If I understand correctly, we should be aiming to target .NET Standard 2.1 and .NET 6

**Comment by Morilli** [comment]
If I'm reading that guide correctly, there are only two reasonable paths:
1. Support .netstandard 2.0 and .net6, to cover both .net framework implementations (netstandard) and modern supported .NET versions (.net6)
2. Target only .net6, which won't support .net framework but supports all current and coming supported .NET versions (.NET 6, 7, 8...)

I personally would prefer the second approach here, especially since fitting in .netstandard 2.0 is probably a considerable effort and multi-targeting makes using new .NET6+ only features more complicated, as they need to be `#if`-guarded and maintained properly.

Of note, targeting both .netstandard 2.1 and .net6 seems to be of no use, as that only adds support for .netcore 3.0 and 3.1, which are both end-of-life.

**Comment by Crauzer** [comment]
> I personally would prefer the second approach here, especially since fitting in .netstandard 2.0 is probably a considerable effort and multi-targeting makes using new .NET6+ only features more complicated, as they need to be #if-guarded and maintained properly.
Of note, targeting both .netstandard 2.1 and .net6 seems to be of no use, as that only adds support for .netcore 3.0/3.1 and .NET 5, which are all end-of-life.

This is a very strong point, going forward, I think it's reasonable to consider all .NET versions below 5 as legacy/obsolete since they're a part of the old ecosystem which is not worth maintaining support for, and as you mention, with each new public API will come new challenges in how to correctly maintain it without having to go through various hoops such as `#if`-guards or polyfills which might make it more difficult to develop.

**Comment by Rerago** [comment]
As I said, it was also just an idea. Since I would generally always make a MultiTarget as long as it would not make any big problems/circumstances. 

In the case of an API for League this is probably not so tragic to simply target the highest. Since you can assume a pretty homogeneous environment here.

But I personally will try to target my libs on .net Standard 2.0 at least as long as .net Framework is still preinstalled on current Windows versions.
